### ISSUE TITLE
UnknownAllocationDevice for XNNPACK

### ISSUE THREAD

**Issue by marcown** [pykeio/ort#275]
Hey there, thanks for the nice package. I am trying to use xnnpack but get the following error:

```bash
called `Result::unwrap()` on an `Err` value: UnknownAllocationDevice("XnnpackExecutionProvider")
```

This is my code:

```toml
ort = { version = "2.0.0-rc.5", features = [ "xnnpack"] }
```

```rust

        let session = Session::builder()
            .unwrap()
            .with_optimization_level(GraphOptimizationLevel::Level3)
            .unwrap()
            .with_intra_threads(4)
            .unwrap()
            .with_execution_providers([ XNNPACKExecutionProvider::default().build().error_on_failure())
            .unwrap()
            .commit_from_memory(onnx_model)
            .unwrap();

```

As I understand for XNNPACK static libraries should be provided automatically. Is there another option I am not seeing?

Thanks!

**Comment by decahedron1** [comment]
This was fixed in https://github.com/pykeio/ort/commit/6807a680570757943a1f39b89eb4b61c35f75f5e; until rc6 releases, you can use `ort` as a git dependency:
```toml
[dependencies]
ort = { git = "https://github.com/pykeio/ort.git", rev = "6807a680570757943a1f39b89eb4b61c35f75f5e", features = [ "xnnpack" ] }
```
