### ISSUE TITLE
v2.0.0-rc.7 compilation failure, error[E0308]: mismatched types

### ISSUE THREAD

**Issue by martynas-subonis** [pykeio/ort#303]
# Environment

**Host System:**
OS: MacOS 15.0.1
Chip: Apple M2 Max
Memory: 64GB

Docker Desktop 4.34.3
Docker Engine v27.2.0

**Dockerfile Stage:**
```Dockerfile

FROM rust:1.82 AS builder
WORKDIR /app

COPY Cargo.toml Cargo.lock main.rs ./
RUN cargo build --release
```

**cargo.toml:**
```toml
[[bin]]
name = "rust_onnx_serving"
path = "main.rs"

[dependencies]
actix-web = "4.9.0"
google-cloud-storage = "0.22.1"
image = { version = "0.25.4", features = ["jpeg", "png"] }
ndarray = "0.16.1"
ort = { version = "2.0.0-rc.7" }
serde = { version = "1.0.210", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
tracing-opentelemetry = "0.27.0"
opentelemetry = { version = "0.26.0" }
opentelemetry_sdk = "0.26.0"
opentelemetry-stdout = "0.26.0"
```

# Compilation Error

```logs
29.08 error[E0308]: mismatched types
29.08    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/ort-2.0.0-rc.7/src/session/builder/impl_options.rs:144:77
29.08     |
29.08 144 |         ortsys![unsafe AddExternalInitializers(self.session_options_ptr.as_ptr(), &name.as_ptr().cast::<i8>(), &value.ptr().cast_const...
29.08     |                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*const *const u8`, found `&*const i8`
29.08     |
29.08    ::: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/ort-2.0.0-rc.7/src/lib.rs:263:44
29.08     |
29.08 263 | ...safe { $crate::api().as_ref().$method.unwrap_or_else(|| unreachable!(concat!("Method `", stringify!($method), "` is null")))($($n),+) ...
29.08     |           --------------------------------------------------------------------------------------------------------------------- arguments to this function are incorrect
29.08     |
29.08     = note: expected raw pointer `*const *const u8`
29.08                  found reference `&*const i8`
29.08
29.09 error[E0308]: mismatched types
29.09    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/ort-2.0.0-rc.7/src/session/builder/impl_options.rs:156:108
29.09     |
29.09 156 | ...(), &file_name.as_ptr(), &buffer.as_ptr().cast::<i8>().cast_mut(), sizes.as_ptr(), 1)?];
29.09     |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*const *mut u8`, found `&*mut i8`
29.09     |
29.09    ::: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/ort-2.0.0-rc.7/src/lib.rs:263:44
29.09     |
29.09 263 | ...safe { $crate::api().as_ref().$method.unwrap_or_else(|| unreachable!(concat!("Method `", stringify!($method), "` is null")))($($n),+) ...
29.09     |           --------------------------------------------------------------------------------------------------------------------- arguments to this function are incorrect
29.09     |
29.09     = note: expected raw pointer `*const *mut u8`
29.09                  found reference `&*mut i8`
29.09
29.55 For more information about this error, try `rustc --explain E0308`.
29.56 error: could not compile `ort` (lib) due to 2 previous errors
29.56 warning: build failed, waiting for other jobs to finish...
------
failed to solve: process "/bin/sh -c cargo build --release" did not complete successfully: exit code: 101
```

# Additional Information

Running `cargo build --release` directly on MacOS succeeds for the same setup. Compilation only fails when running it on Debian based `rust:1.82` image.
