### ISSUE TITLE
[windows] cannot compile with ort because of linker error LNK2038

### ISSUE THREAD

**Issue by luong-komorebi** [pykeio/ort#329]
I am working on a project that uses [fastembed](https://github.com/Anush008/fastembed-rs) which under the hood uses `ort`. When I try compiling on a recent build of Windows 10 with `Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.42.34433\`, what I expect is a flawless compilation accroding to the platform support documented [here](https://ort.pyke.io/setup/platforms) 

However, I keep seeing this error :

```
error: linking with `link.exe` failed: exit code: 1319

<stripped content because it is just paths to msvc and related files >

= note: libesaxx_rs-cf1ba299408f1feb.rlib(2e40c9e35e9506f4-esaxx.o) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in libort_sys-ec614dd3849d8d4b.rlib(onnxruntime_c_api.obj)␍
```

and could not get pass it. I have tried multiple methods to work around this, such as forcing `target-feature=+crt-static` and compiling onnx runtime from source then link it to cargo build via ORT_LIB_LOCATION as an environment variable but none works. The only thing I haven't tried is dynamic linking with `load-dynamic`. 

This also happens on github action with `windows-latest`. 

My workflow looks something like this 

```yaml
      - name: compile ONNX Runtime from source
        run: |
          git clone --recursive https://github.com/Microsoft/onnxruntime.git
          cd onnxruntime
          python -m pip install cmake
          .\build.bat --config Release --parallel --compile_no_warning_as_error --skip_submodule_sync  --skip_tests
      - name: Cargo build
        shell: bash
        env:
          DUCKDB_LIB_DIR: ${{ github.workspace }}/libduckdb
          DUCKDB_INCLUDE_DIR: ${{ github.workspace }}/libduckdb
          LD_LIBRARY_PATH: ${{ github.workspace }}/libduckdb
          ORT_LIB_LOCATION: ${{ github.workspace }}/onnxruntime/build/Windows/Release
        run: |
          cargo build --release --target ${{ matrix.job.target }}
```

I dont understand the internal working of ort and there are not many documentations about this linker issue so I open this issue for some help. Thank you in advance for your time.

**Comment by decahedron1** [comment]
This is because `esaxx-rs` will [always link CRT statically](https://github.com/Narsil/esaxx-rs/blob/5a573faadada925d25c39d5e0f6af7da596cef4e/build.rs#L7C13-L7C13), while ONNX Runtime links CRT dynamically by default.

This issue is related to https://github.com/Narsil/esaxx-rs/issues/13. There's a fix in https://github.com/Narsil/esaxx-rs/pull/14, but it hasn't been merged yet. If you don't publish your crate on crates.io you can use `esaxx` as a Git dependency pinned to the fixed fork instead:
```toml
[dependencies]
esaxx-rs = { git = "https://github.com/thewh1teagle/esaxx-rs.git", branch = "feat/dynamic-msvc-link" }
```
