### ISSUE TITLE
🚨 Pre-rc.10 users: Pin `ort-sys` in `[dependencies]`

### ISSUE THREAD

**Issue by decahedron1** [pykeio/ort#399]
Version `2.0.0-rc.10` of `ort-sys` was recently released. This version contains breaking changes.

Versions of `ort` prior to rc.10 **did not pin the `ort-sys` version**, so when resolving dependencies, Cargo will try to use the latest version of `ort-sys`, breaking your build.

You can fix this by pinning the version of `ort-sys` in your `Cargo.toml`:
```toml
[dependencies]
ort-sys = { version = "=2.0.0-rc.9", default-features = false } # match whatever version of `ort` you use
```

In Cargo workspaces, make sure you're using the v2 resolver:
```toml
[workspace]
resolver = "2"
```
