### ISSUE TITLE
Build error for 2.0.0-rc.10

### ISSUE THREAD

**Issue by blackberryfloat** [pykeio/ort#406]
I am building for a wasm target with the ort-tract backend and the build wont pass. I believe this is an error with the crate and not my dependency tree. Here is my Cargo.toml snippet:

```
ort-sys = { version = "=2.0.0-rc.10", default-features = false }
ort = {version="2.0.0-rc.10", features=["cuda", "tensorrt"]}
ndarray = "0.16.1"
reqwest = {version = "0.12.19", features=["blocking", "json"]}
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uuid = { version = "1.17.0", features = ["v4", "serde"] }
webbrowser = "1.0.4"

[package.metadata.cargo-machete]
ignored = ["egui_extras"]

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = [ "env-filter", "fmt" ] }
wasm-bindgen-test = "0.3.50"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rfd = "0.15.3"
tokio = { version = "1.45.1", features = ["rt", "rt-multi-thread", "fs", "io-std", "macros"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
ort = { version = "2.0.0-rc.10", default-features = false, features = ["alternative-backend"]}
ort-tract = "0.1.0+0.21"
wasm_file_system_api = { path = "../wasm_file_system_api"}
web-sys = {version="0.3.77", features=["FileSystemFileHandle", "FileSystemDirectoryHandle"]}
wasm-bindgen-futures = "0.4.50"

[target.'cfg(target_os = "macos")'.dependencies]
ort = { version = "2.0.0-rc.10", features = ["coreml"] }

[target.'cfg(target_os = "windows")'.dependencies]
ort = { version = "2.0.0-rc.10", features = ["directml"] }
```

Error

```
ort-2.0.0-rc.10/src/util.rs:54:31
   |
54 |     let path: Vec<c_char> = path.as_bytes().iter().chain(std::iter::once(&b'\0')).map(|b| *b as c_char).collect();
   |                                  ^^^^^^^^
   |
help: there is a method `as_encoded_bytes` with a similar name
   |
54 -     let path: Vec<c_char> = path.as_bytes().iter().chain(std::iter::once(&b'\0')).map(|b| *b as c_char).collect();
54 +     let path: Vec<c_char> = path.as_encoded_bytes().iter().chain(std::iter::once(&b'\0')).map(|b| *b as c_char).collect();
   |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `ort` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by decahedron1** [comment]
Are you compiling for a WASI target?

**Comment by blackberryfloat** [comment]
No. wasm32-unknown-unknown

**Comment by blackberryfloat** [comment]
I see. I assume that is the issue. Sorry this is my first foray into wasm. Been using desktop builds for ort.

**Comment by decahedron1** [comment]
No, `wasm32-unknown-unknown` should work, I just asked because I spotted a similar issue for WASI. Let me see if I can fix this for `wasm32-unknown-unknown`.

**Comment by blackberryfloat** [comment]
Oh. Thanks. It has been a while since I looked up the difference between wasm and wasi so I did a quick search just now and it made me think wasi was necessary to interact with hardware. I need to do some more reading.

**Comment by decahedron1** [comment]
For `wasm32-unknown-unknown`, ort's `std` feature should be disabled. I think that specifying `default-features = false` in the target-specific dependency doesn't override the base dependency's features; the features defined there are *additive*, so you can't *remove* features via `[target.*.dependencies]`. Your `Cargo.toml` should instead look something like:
```toml
[dependencies]
ort = {version="2.0.0-rc.10", default-features=false, features=["ndarray"]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ort = {version="2.0.0-rc.10", features=["cuda", "tensorrt"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
ort = { version = "2.0.0-rc.10", default-features = false, features = ["alternative-backend"]}
```

Additionally, the `ndarray` feature without `std` is broken in rc.10, so you should instead use [this patched commit](https://github.com/pykeio/ort/commit/22f71ba86a0cced9e2471ecb4b104b53075732ef) by replacing `version = "2.0.0-rc.10"` with `git = "https://github.com/pykeio/ort.git", rev = "22f71ba"`:
```toml
[dependencies]
ort = {git = "https://github.com/pykeio/ort.git", rev = "22f71ba", default-features=false, features=["ndarray"]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ort = {git = "https://github.com/pykeio/ort.git", rev = "22f71ba", features=["cuda", "tensorrt"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
ort = { git = "https://github.com/pykeio/ort.git", rev = "22f71ba", default-features = false, features = ["alternative-backend"]}
```

(you should also remove the `ort-sys` dependency as well)
