### ISSUE TITLE
Static linking of ONNX runtime

### ISSUE THREAD

**Issue by raphaelmenges** [pykeio/ort#68]
Hello 👋

Is there a way to link the ONNX runtime library statically (`.a`, `.lib`) into the outputted binary? This would simplify deployment!

You can find static builds of the ONNX runtime here: <https://github.com/supertone-inc/onnxruntime-build/tree/main>

Cheers,
Raphael

**Comment by decahedron1** [comment]
Yes, static linking is supported with `ORT_STRATEGY=system`: https://github.com/pykeio/ort/blob/d7defd1862969b4b44f7f3f4b9c72263690bd67b/build.rs#L333-L398

However I have not yet tested this with ONNX Runtime 1.15.1 so it may need some modification. Please let me know if you run into any issues.

**Comment by raphaelmenges** [comment]
Works for me with ONNX Runtime 1.15.1, thanks!

I found it convenient to define the environment in `.cargo/config.toml` as follows:

```toml
[env]
ORT_STRATEGY = { value = "system" }
ORT_LIB_LOCATION = { value = "vendor/lib" , relative = true }
```

Providing the static ort library under `vendor/lib`, no further build preparation on the system has to be performed at all :)
